jobs:
- name: deploy-haproxy
  plan:
  - in_parallel:
    - get: stemcell
    - get: manifest
  - put: deploy
    params:
      manifest: manifest/manifest.yml
      stemcells: [ stemcell/stemcell.tgz ]

resources:
- name: manifest
  type: file
  source:
    filename: manifest.yml
    content:
      name: haproxy
      releases:
      - name: "haproxy"
        version: "9.7.0"
        url: "https://bosh.io/d/github.com/cloudfoundry-community/haproxy-boshrelease?v=9.7.0"
        sha1: "a0219a8ea6313fb122fdfcc2fa1654b90780d71b"
      - name: bpm
        url: https://bosh.io/d/github.com/cloudfoundry/bpm-release?v=1.1.3
        version: 1.1.3
        sha1: b41556af773ea9aec93dd21a9bbf129200849eed
      instance_groups:
      - name: haproxy
        vm_extensions: [ haproxy-network-properties ]
        jobs:
        - name: bpm
          release: bpm
        - name: haproxy
          release: haproxy
          properties:
            ha_proxy:
              ssl_pem:
                - cert_chain: ((/((bosh_name))/haproxy/haproxy_ssl.certificate))((/((bosh_name))/haproxy/haproxy_ssl.ca))
                  private_key: ((/((bosh_name))/haproxy/haproxy_ssl.private_key))
              raw_config: |
                global
                    log /dev/log len 1024 format rfc3164 syslog info
                    daemon
                        user vcap
                    group vcap
                    maxconn 64000
                    spread-checks 4
                    tune.ssl.default-dh-param 2048
                    tune.bufsize 16384
                    stats socket /var/vcap/sys/run/haproxy/stats.sock mode 600 level admin
                    stats timeout 2m
                    ssl-default-bind-options no-sslv3 no-tls-tickets
                    ssl-default-bind-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS
                    ssl-default-server-options no-sslv3 no-tls-tickets
                    ssl-default-server-ciphers ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS

                defaults
                    log global
                    option log-health-checks
                    option log-separate-errors
                    maxconn 64000
                    option http-server-close
                    option httplog
                    option forwardfor
                    option contstats
                    timeout connect         5000ms
                    timeout client          30000ms
                    timeout server          30000ms
                    timeout tunnel          3600000ms
                    timeout http-keep-alive 6000ms
                    timeout http-request    5000ms
                    timeout queue           30000ms

                resolvers dns
                    nameserver bosh-dns-0  169.254.0.2:53
                    hold valid 1s

                frontend http-in
                    mode http
                    bind :80
                    capture request header Host len 256
                    redirect scheme https code 301

                frontend https-in
                    mode http
                    bind :443 ssl crt /var/vcap/jobs/haproxy/config/ssl
                    capture request header Host len 256
                    acl xfp_exists hdr_cnt(X-Forwarded-Proto) gt 0
                    reqadd X-Forwarded-Proto:\ https if ! xfp_exists
                    use_backend cf0 if { hdr_end(host) -i hol.starkandwayne.com }

                backend cf0
                    mode http
                    balance roundrobin
                    server router0 q-s0.router.default.cf.bosh:443 resolvers dns check inter 1000 ssl verify none

        instances: 2
        vm_type: default
        stemcell: default
        networks:
        - name: default
        azs:
        - z1
        - z2
      stemcells:
      - alias: default
        os: ubuntu-xenial
        version: latest
      update:
        canaries: 1
        max_in_flight: 1
        canary_watch_time: 1000-30000
        update_watch_time: 1000-30000
      variables:
      - name: haproxy_ca
        type: certificate
        options:
          is_ca: true
          common_name: haproxyCA
      - name: haproxy_ssl
        type: certificate
        options:
          ca: haproxy_ca
          common_name: haproxySSL
          alternative_names:
          - hol.starkandwayne.com
          - "*.hol.starkandwayne.com"

- name: stemcell
  type: bosh-io-stemcell
  source: { name: ((bosh_stemcell)) }

- name: deploy
  type: bosh-deployment
  source:
    deployment: haproxy
    target: ((bosh_environment))
    client: ((bosh_client))
    client_id: ((bosh_client))
    client_secret: ((bosh_client_secret))
    ca_cert: ((bosh_ca_cert))

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
    tag: latest

- name: file
  type: docker-image
  source:
    repository: aequitas/concourse-file-resource
    tag: latest
