director__external_ip: 35.234.95.218
director__internal_ip: 10.0.0.6
director__tags:
- hol-user-12-bosh-director
director_address: https://35.234.110.165:25555
director_name: bosh-hol-user-12
external_ip: 35.234.110.165
internal_cidr: 10.0.0.0/16
internal_gw: 10.0.0.1
internal_tag_name: hol-user-12-internal
jumpbox__external_ip: 35.234.110.165
jumpbox__internal_ip: 10.0.0.5
jumpbox__tags:
- hol-user-12-bosh-open
- hol-user-12-jumpbox
jumpbox_url: 35.234.110.165:22
network: hol-user-12-network
subnetwork: hol-user-12-subnet
subnetwork_reserved_ips: 10.0.0.1-10.0.0.255
subnetwork_static_ips: 10.0.255.0-10.0.255.254
