director__external_ip: 35.234.108.203
director__internal_ip: 10.0.0.6
director__tags:
- hol-user-9-bosh-director
director_address: https://35.198.110.207:25555
director_name: bosh-hol-user-9
external_ip: 35.198.110.207
internal_cidr: 10.0.0.0/16
internal_gw: 10.0.0.1
internal_tag_name: hol-user-9-internal
jumpbox__external_ip: 35.198.110.207
jumpbox__internal_ip: 10.0.0.5
jumpbox__tags:
- hol-user-9-bosh-open
- hol-user-9-jumpbox
jumpbox_url: 35.198.110.207:22
network: hol-user-9-network
subnetwork: hol-user-9-subnet
subnetwork_reserved_ips: 10.0.0.1-10.0.0.255
subnetwork_static_ips: 10.0.255.0-10.0.255.254
