- type: replace
  path: /vm_extensions?/name=worker_lb?
  value:
    name: worker_lb
    cloud_properties:
      target_pool: ((worker_pool_name))
      tags: ((worker_tags))
- type: replace
  path: /vm_extensions?/name=master_lb?
  value:
    name: master_lb
    cloud_properties:
      target_pool: ((master_pool_name))
      tags: ((master_tags))
- type: replace
  path: /vm_types/name=medium
  value:
    cloud_properties:
      machine_type: n1-standard-4
      root_disk_size_gb: 64
    name: medium
