director__external_ip: 35.198.100.0
director__internal_ip: 10.0.0.6
director__tags:
- hol-user-10-bosh-director
director_address: https://35.198.98.37:25555
director_name: bosh-hol-user-10
external_ip: 35.198.98.37
internal_cidr: 10.0.0.0/16
internal_gw: 10.0.0.1
internal_tag_name: hol-user-10-internal
jumpbox__external_ip: 35.198.98.37
jumpbox__internal_ip: 10.0.0.5
jumpbox__tags:
- hol-user-10-bosh-open
- hol-user-10-jumpbox
jumpbox_url: 35.198.98.37:22
network: hol-user-10-network
subnetwork: hol-user-10-subnet
subnetwork_reserved_ips: 10.0.0.1-10.0.0.255
subnetwork_static_ips: 10.0.255.0-10.0.255.254
