director__external_ip: 35.241.172.196
director__internal_ip: 10.0.0.6
director__tags:
- hol-user-1-bosh-director
director_address: https://35.195.38.218:25555
director_name: bosh-hol-user-1
external_ip: 35.195.38.218
internal_cidr: 10.0.0.0/16
internal_gw: 10.0.0.1
internal_tag_name: hol-user-1-internal
jumpbox__external_ip: 35.195.38.218
jumpbox__internal_ip: 10.0.0.5
jumpbox__tags:
- hol-user-1-bosh-open
- hol-user-1-jumpbox
jumpbox_url: 35.195.38.218:22
network: hol-user-1-network
subnetwork: hol-user-1-subnet
subnetwork_reserved_ips: 10.0.0.1-10.0.0.255
subnetwork_static_ips: 10.0.255.0-10.0.255.254
